// LAS Data File

export const data = [
  {
    name: 'Bajaj Finserv',
    approvedStocks: '1000+',
    tenure: '36 Months & Renewal',
    loanRange: '₹25K – ₹1000Cr',
    minRate: '8%',

    // Cost & Returns
    maxRate: '15%',
    medianRate: '12%',
    processingFee: '4.72%',
    renewalFee: '1.18%',
    penalCharges: '10.50%',
    firstYearPercent: '16.22%',
    firstYearAmount: '₹16,220',
    secondYearPercent: '12.68%',
    secondYearAmount: '₹12,680',

    // Operational
    ltvMin: '20%',
    turnaround: '24hrs',
    digitalProcess: 'Yes',
    rating: '4.5/5',
  },
  {
    name: 'SBI',
    approvedStocks: '1000+',
    tenure: '12 Months & Renewal',
    loanRange: '₹25K – ₹20L',
    minRate: '11.5%',

    maxRate: '11.5%',
    medianRate: '12%',
    processingFee: '0.75%',
    renewalFee: '₹550',
    penalCharges: '13.50%',
    firstYearPercent: '13.50%',
    firstYearAmount: '₹13,500',
    secondYearPercent: '13.05%',
    secondYearAmount: '₹13,050',

    ltvMin: 'N/A',
    turnaround: '48hrs',
    digitalProcess: 'Partial',
    rating: '4.2/5',
  },
  {
    name: 'HDFC Securities',
    approvedStocks: '950+',
    tenure: '24 Months',
    loanRange: '₹50K – ₹50Cr',
    minRate: '9%',

    maxRate: '13%',
    medianRate: '11%',
    processingFee: '2%',
    renewalFee: '₹999',
    penalCharges: '12%',
    firstYearPercent: '12.5%',
    firstYearAmount: '₹12,500',
    secondYearPercent: '11.2%',
    secondYearAmount: '₹11,200',

    ltvMin: '25%',
    turnaround: '36hrs',
    digitalProcess: 'Yes',
    rating: '4.3/5',
  },
  {
    name: 'ICICI Direct',
    approvedStocks: '900+',
    tenure: '18 Months',
    loanRange: '₹1L – ₹25Cr',
    minRate: '9.5%',

    maxRate: '14%',
    medianRate: '11.8%',
    processingFee: '1.5%',
    renewalFee: '₹850',
    penalCharges: '12.75%',
    firstYearPercent: '12.9%',
    firstYearAmount: '₹12,900',
    secondYearPercent: '11.6%',
    secondYearAmount: '₹11,600',

    ltvMin: '22%',
    turnaround: '24hrs',
    digitalProcess: 'Yes',
    rating: '4.4/5',
  },
  {
    name: 'Kotak Securities',
    approvedStocks: '850+',
    tenure: '24 Months',
    loanRange: '₹50K – ₹15Cr',
    minRate: '10%',

    maxRate: '14%',
    medianRate: '12%',
    processingFee: '2.25%',
    renewalFee: '₹750',
    penalCharges: '13%',
    firstYearPercent: '13.2%',
    firstYearAmount: '₹13,200',
    secondYearPercent: '12%',
    secondYearAmount: '₹12,000',

    ltvMin: '20%',
    turnaround: '30hrs',
    digitalProcess: 'Partial',
    rating: '4.1/5',
  },
  {
    name: 'Axis Bank',
    approvedStocks: '920+',
    tenure: '12 Months',
    loanRange: '₹1L – ₹10Cr',
    minRate: '9%',

    maxRate: '13.5%',
    medianRate: '11.2%',
    processingFee: '1.2%',
    renewalFee: '₹600',
    penalCharges: '12.25%',
    firstYearPercent: '12.8%',
    firstYearAmount: '₹12,800',
    secondYearPercent: '11.4%',
    secondYearAmount: '₹11,400',

    ltvMin: '23%',
    turnaround: '48hrs',
    digitalProcess: 'Yes',
    rating: '4.0/5',
  },
  {
    name: 'Motilal Oswal',
    approvedStocks: '800+',
    tenure: '24 Months',
    loanRange: '₹75K – ₹30Cr',
    minRate: '10.2%',

    maxRate: '14.5%',
    medianRate: '12.3%',
    processingFee: '1.8%',
    renewalFee: '₹900',
    penalCharges: '13.25%',
    firstYearPercent: '13.7%',
    firstYearAmount: '₹13,700',
    secondYearPercent: '12.2%',
    secondYearAmount: '₹12,200',

    ltvMin: '21%',
    turnaround: '72hrs',
    digitalProcess: 'Partial',
    rating: '4.0/5',
  },
  {
    name: 'Reliance Securities',
    approvedStocks: '780+',
    tenure: '18 Months',
    loanRange: '₹50K – ₹8Cr',
    minRate: '11%',

    maxRate: '15%',
    medianRate: '13%',
    processingFee: '2.5%',
    renewalFee: '₹700',
    penalCharges: '13.75%',
    firstYearPercent: '14%',
    firstYearAmount: '₹14,000',
    secondYearPercent: '12.8%',
    secondYearAmount: '₹12,800',

    ltvMin: '19%',
    turnaround: '96hrs',
    digitalProcess: 'No',
    rating: '3.8/5',
  },
  {
    name: 'Yes Bank',
    approvedStocks: '820+',
    tenure: '12 Months',
    loanRange: '₹1L – ₹12Cr',
    minRate: '9.8%',

    maxRate: '13.8%',
    medianRate: '12%',
    processingFee: '1.4%',
    renewalFee: '₹650',
    penalCharges: '12.6%',
    firstYearPercent: '13%',
    firstYearAmount: '₹13,000',
    secondYearPercent: '11.7%',
    secondYearAmount: '₹11,700',

    ltvMin: '20%',
    turnaround: '36hrs',
    digitalProcess: 'Yes',
    rating: '4.1/5',
  },
  {
    name: 'Edelweiss',
    approvedStocks: '700+',
    tenure: '24 Months',
    loanRange: '₹50K – ₹7Cr',
    minRate: '10.5%',

    maxRate: '14%',
    medianRate: '12.5%',
    processingFee: '2%',
    renewalFee: '₹500',
    penalCharges: '13%',
    firstYearPercent: '13.8%',
    firstYearAmount: '₹13,800',
    secondYearPercent: '12.4%',
    secondYearAmount: '₹12,400',

    ltvMin: '18%',
    turnaround: '72hrs',
    digitalProcess: 'Partial',
    rating: '3.9/5',
  },
];
